import 'dart:convert';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:io';

class Autogenerated {
  late List<StateImages> stateImages;

  Autogenerated({required this.stateImages});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['StateImages'] != null) {
      stateImages = <StateImages>[];
      json['StateImages'].forEach((v) {
        stateImages.add(StateImages.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (stateImages != null) {
      data['StateImages'] = stateImages.map((v) => v.toJson()).toList();
    }
    return data;
  }

  //保存文件 loginSave.json
  static createLoginSaveFlie(Autogenerated data, String strPath) async {
    // 登陆成功创建一个文件，文件存在就保存数据
    try {
      //保存路径
      String savePath = strPath;
      File jsonFile = File(savePath);
      //判断文件是否存在
      if (!jsonFile.existsSync()) {
        //文件不存在创建文件
        jsonFile.createSync();
        print('$strPath创建成功');
      } else {
        print('$strPath文件已存在');
      }

      // json文件写入
      // studentToJson(data);
      jsonFile.writeAsString(json.encode(data.toJson()));
    } catch (e) {
      print('$strPath创建失败');
    }
  }
}

class StateImages {
  late List<WorkId> workId;

  StateImages({required this.workId});

  StateImages.fromJson(Map<String, dynamic> json) {
    if (json['workId'] != null) {
      workId = <WorkId>[];
      json['workId'].forEach((v) {
        workId.add(WorkId.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (workId != null) {
      data['workId'] = workId.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class WorkId {
  late int id;
  late int workPoint;
  late int productPoint;
  late int nStateImages;

  WorkId({required this.id, required this.workPoint, required this.productPoint, required this.nStateImages});

  WorkId.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    workPoint = json['workPoint'];
    productPoint = json['productPoint'];
    nStateImages = json['nStateImages'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['workPoint'] = workPoint;
    data['productPoint'] = productPoint;
    data['nStateImages'] = nStateImages;
    return data;
  }
}



